export const ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST" = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS" = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAILED: "ORDER_DETAILS_FAILED" = 'ORDER_DETAILS_FAILED';
export const ORDER_DETAILS_CLOSE_MODAL: "ORDER_DETAILS_CLOSE_MODAL" = 'ORDER_DETAILS_CLOSE_MODAL';